/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Elementos_Curvas_Circulares.login;

import static java.lang.Math.pow;
import static java.lang.Math.sqrt;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/**
 *
 * @author jenni
 */
public class ElementosCurvasCirculares extends javax.swing.JFrame {

    /**
     * Creates new form ElementosCurvasCirculares
     */
    public ElementosCurvasCirculares() {
        initComponents();
    }

    public class CurvaCircularPanel extends JPanel {
    private int radio;
    private double anguloMitad;

    public CurvaCircularPanel(int radio, double anguloMitad) {
        this.radio = radio;
        this.anguloMitad = anguloMitad;

        setPreferredSize(new Dimension(400, 400));
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int centroX = getWidth() / 2;
        int centroY = getHeight() / 2;
        int diametro = radio * 2;

        int inicioAngulo = 90 - (int) Math.toDegrees(anguloMitad);
        int arcoAngulo = (int) Math.toDegrees(anguloMitad) * 2;

        g2d.setColor(Color.BLACK);
        g2d.drawArc(centroX - radio, centroY - radio, diametro, diametro, inicioAngulo, arcoAngulo);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Delta = new javax.swing.JTabbedPane();
        P2 = new javax.swing.JPanel();
        P2X = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        P2X1 = new javax.swing.JTextField();
        P2X2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        P3 = new javax.swing.JPanel();
        P3X = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        P1 = new javax.swing.JPanel();
        P1X = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        N1 = new javax.swing.JTextField();
        N2 = new javax.swing.JTextField();
        E1 = new javax.swing.JTextField();
        E2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lb_LONGITUDDECURVA = new javax.swing.JLabel();
        txt_DEFLEXIONPARA10m = new javax.swing.JTextField();
        lb_TANGENTE1 = new javax.swing.JLabel();
        txt_TANGENTE1 = new javax.swing.JTextField();
        lb_FLECHA = new javax.swing.JLabel();
        lb_EXTERNA = new javax.swing.JLabel();
        lb_DISTANCIAHORIZ = new javax.swing.JLabel();
        lb_ENTRETANGENTE = new javax.swing.JLabel();
        lb_DEFLEXIONPARA10m = new javax.swing.JLabel();
        lb_DEFLEXIONPARA1m = new javax.swing.JLabel();
        lb_CUERDAPRINCIPAL = new javax.swing.JLabel();
        txt_DISTANCIAHORIZ = new javax.swing.JTextField();
        txt_EXTERNA = new javax.swing.JTextField();
        txt_FLECHA = new javax.swing.JTextField();
        txt_LONGITUDDECURVA = new javax.swing.JTextField();
        txt_CUERDAPRINCIPAL = new javax.swing.JTextField();
        txt_DEFLEXIONPARA1m = new javax.swing.JTextField();
        txt_ENTRETANGENTE = new javax.swing.JTextField();
        SALIDA = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        imagen3 = new javax.swing.JLabel();
        imagen1 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        lb_TANGENTE9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(102, 102, 102));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_titulo.setBackground(new java.awt.Color(255, 255, 255));
        lb_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lb_titulo.setText("CALCULAR - ELEMENTOS DE CURVA CIRCULAR");
        bg.add(lb_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 460, 20));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, 430));

        Delta.setBackground(new java.awt.Color(255, 255, 255));
        Delta.setBorder(new javax.swing.border.MatteBorder(null));

        P2.setBackground(new java.awt.Color(255, 255, 255));

        P2X.setBackground(new java.awt.Color(240, 240, 240));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("DELTA");

        P2X1.setBackground(new java.awt.Color(240, 240, 240));

        P2X2.setBackground(new java.awt.Color(240, 240, 240));

        jLabel1.setText("Grados");

        jLabel3.setText("Min");

        jLabel4.setText("Seg");

        javax.swing.GroupLayout P2Layout = new javax.swing.GroupLayout(P2);
        P2.setLayout(P2Layout);
        P2Layout.setHorizontalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel13)
                .addGap(39, 39, 39)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P2Layout.createSequentialGroup()
                        .addComponent(P2X, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P2X1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(P2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)))
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P2X2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)))
                .addGap(36, 36, 36))
        );
        P2Layout.setVerticalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P2X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(P2X1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P2X2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Delta.addTab("DELTA", P2);

        P3.setBackground(new java.awt.Color(255, 255, 255));

        P3X.setBackground(new java.awt.Color(240, 240, 240));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("RADIO");

        javax.swing.GroupLayout P3Layout = new javax.swing.GroupLayout(P3);
        P3.setLayout(P3Layout);
        P3Layout.setHorizontalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(41, 41, 41)
                .addComponent(P3X, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        P3Layout.setVerticalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P3X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Delta.addTab("RADIO", P3);

        P1.setBackground(new java.awt.Color(255, 255, 255));

        P1X.setBackground(new java.awt.Color(240, 240, 240));
        P1X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1XActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("GRADO DE CURVA");

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(P1X, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(P1X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Delta.addTab("GRADO CURVA", P1);

        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });

        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });

        jLabel5.setText("N1");

        jLabel6.setText("N2");

        jLabel7.setText("E1");

        jLabel8.setText("E2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(N1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(N2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Delta.addTab("COORDENADAS", jPanel1);

        bg.add(Delta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 110));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("RESULTADOS");
        bg.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        lb_LONGITUDDECURVA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_LONGITUDDECURVA.setText("LONGITUD DE CURVA");
        bg.add(lb_LONGITUDDECURVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 130, -1));

        txt_DEFLEXIONPARA10m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DEFLEXIONPARA10mActionPerformed(evt);
            }
        });
        bg.add(txt_DEFLEXIONPARA10m, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 150, -1));

        lb_TANGENTE1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_TANGENTE1.setText("TANGENTE");
        bg.add(lb_TANGENTE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 130, 30));

        txt_TANGENTE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TANGENTE1ActionPerformed(evt);
            }
        });
        bg.add(txt_TANGENTE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 150, -1));

        lb_FLECHA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_FLECHA.setText("FLECHA");
        bg.add(lb_FLECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, -1));

        lb_EXTERNA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_EXTERNA.setText("EXTERNA");
        bg.add(lb_EXTERNA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 130, -1));

        lb_DISTANCIAHORIZ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_DISTANCIAHORIZ.setText("DISTANCIA HORIZ");
        bg.add(lb_DISTANCIAHORIZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 130, -1));

        lb_ENTRETANGENTE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_ENTRETANGENTE.setText("ENTRE TANGENTE");
        bg.add(lb_ENTRETANGENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 130, -1));

        lb_DEFLEXIONPARA10m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_DEFLEXIONPARA10m.setText("DEFLEXION PARA 10m");
        bg.add(lb_DEFLEXIONPARA10m, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 140, -1));

        lb_DEFLEXIONPARA1m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_DEFLEXIONPARA1m.setText("DEFLEXION PARA 1m");
        bg.add(lb_DEFLEXIONPARA1m, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 130, -1));

        lb_CUERDAPRINCIPAL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_CUERDAPRINCIPAL.setText("CUERDA PRINCIPAL");
        bg.add(lb_CUERDAPRINCIPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, -1));

        txt_DISTANCIAHORIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DISTANCIAHORIZActionPerformed(evt);
            }
        });
        bg.add(txt_DISTANCIAHORIZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 150, -1));

        txt_EXTERNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EXTERNAActionPerformed(evt);
            }
        });
        bg.add(txt_EXTERNA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 150, -1));

        txt_FLECHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FLECHAActionPerformed(evt);
            }
        });
        bg.add(txt_FLECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 150, -1));

        txt_LONGITUDDECURVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LONGITUDDECURVAActionPerformed(evt);
            }
        });
        bg.add(txt_LONGITUDDECURVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 150, -1));

        txt_CUERDAPRINCIPAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CUERDAPRINCIPALActionPerformed(evt);
            }
        });
        bg.add(txt_CUERDAPRINCIPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 150, -1));

        txt_DEFLEXIONPARA1m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DEFLEXIONPARA1mActionPerformed(evt);
            }
        });
        bg.add(txt_DEFLEXIONPARA1m, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 150, -1));

        txt_ENTRETANGENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ENTRETANGENTEActionPerformed(evt);
            }
        });
        bg.add(txt_ENTRETANGENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 150, -1));

        SALIDA.setBackground(new java.awt.Color(255, 255, 255));
        SALIDA.setBorder(new javax.swing.border.MatteBorder(null));
        SALIDA.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout SALIDALayout = new javax.swing.GroupLayout(SALIDA);
        SALIDA.setLayout(SALIDALayout);
        SALIDALayout.setHorizontalGroup(
            SALIDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        SALIDALayout.setVerticalGroup(
            SALIDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        bg.add(SALIDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 360, 360));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, -1, -1));

        imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/COLOR1.jpg"))); // NOI18N
        imagen3.setText("jLabel6");
        bg.add(imagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 270));

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/IMAGEN2.jpg"))); // NOI18N
        bg.add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 360, 600));

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/IMAGEN2.jpg"))); // NOI18N
        imagen2.setText("jLabel3");
        bg.add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 400, 600));

        lb_TANGENTE9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_TANGENTE9.setText("TANGENTE");
        bg.add(lb_TANGENTE9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ENTRETANGENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ENTRETANGENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ENTRETANGENTEActionPerformed

    private void txt_DEFLEXIONPARA1mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DEFLEXIONPARA1mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DEFLEXIONPARA1mActionPerformed

    private void txt_CUERDAPRINCIPALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CUERDAPRINCIPALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CUERDAPRINCIPALActionPerformed

    private void txt_LONGITUDDECURVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LONGITUDDECURVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LONGITUDDECURVAActionPerformed

    private void txt_FLECHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FLECHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FLECHAActionPerformed

    private void txt_EXTERNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EXTERNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EXTERNAActionPerformed

    private void txt_DISTANCIAHORIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DISTANCIAHORIZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DISTANCIAHORIZActionPerformed

    private void txt_TANGENTE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TANGENTE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TANGENTE1ActionPerformed

    private void txt_DEFLEXIONPARA10mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DEFLEXIONPARA10mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DEFLEXIONPARA10mActionPerformed

    private void P1XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1XActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P1XActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         
        int Radio=Integer.parseInt(P3X.getText());
        int grados=Integer.parseInt(P2X.getText());
        int minutos=Integer.parseInt(P2X1.getText());
        int segundos=Integer.parseInt(P2X2.getText());
        int n1=Integer.parseInt(N1.getText());
        int n2=Integer.parseInt(N2.getText());
        int e1=Integer.parseInt(E1.getText());
        int e2=Integer.parseInt(E2.getText());
        double gradocurva = 572.96/Radio;
        double decimal = grados + (minutos / 60.0) + (segundos / 3600.0);
        double deltaRadianes = Math.toRadians(decimal);
        double anguloMitad = deltaRadianes / 2;
        double tangente = Radio*Math.tan(anguloMitad);
        double cuerdaPrincipal = 2*Radio*Math.sin(anguloMitad);
        double longituddecurva =(deltaRadianes/gradocurva)*10;
        double flecha = Radio * (1 - Math.cos(anguloMitad));
        double externa = Radio * ((1/Math.cos(anguloMitad))-1 );
        double distaciahoriz = sqrt(pow((n2 - n1), 2)+pow((e2 - e1), 2));
        double entretangente = distaciahoriz - tangente;
        double deflexionpara10m = gradocurva/2;
        double deflexionpara1m = deflexionpara10m/2;
        
        P1X.setText(String.valueOf(gradocurva));
        txt_TANGENTE1.setText(String.valueOf(tangente));
        txt_CUERDAPRINCIPAL.setText(String.valueOf(cuerdaPrincipal));
        txt_LONGITUDDECURVA.setText(String.valueOf(longituddecurva));
        txt_FLECHA.setText(String.valueOf(flecha));
        txt_EXTERNA.setText(String.valueOf(externa));
        txt_DISTANCIAHORIZ.setText(String.valueOf(distaciahoriz));
        txt_ENTRETANGENTE.setText(String.valueOf(entretangente));
        txt_DEFLEXIONPARA10m.setText(String.valueOf(deflexionpara10m));
        txt_DEFLEXIONPARA1m.setText(String.valueOf(deflexionpara1m));
        
         CurvaCircularPanel curvaCircularPanel = new CurvaCircularPanel(Radio, anguloMitad);

    SALIDA.setLayout(new FlowLayout()); // Establecer el administrador de diseño

    SALIDA.removeAll();
    SALIDA.add(curvaCircularPanel);

    // Establecer el tamaño del panel CurvaCircularPanel dentro de SALIDA
    curvaCircularPanel.setPreferredSize(new Dimension(400, 400));

    SALIDA.revalidate();
    SALIDA.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E1ActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N2ActionPerformed
 public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElementosCurvasCirculares().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Delta;
    private javax.swing.JTextField E1;
    private javax.swing.JTextField E2;
    private javax.swing.JTextField N1;
    private javax.swing.JTextField N2;
    private javax.swing.JPanel P1;
    private javax.swing.JTextField P1X;
    private javax.swing.JPanel P2;
    private javax.swing.JTextField P2X;
    private javax.swing.JTextField P2X1;
    private javax.swing.JTextField P2X2;
    private javax.swing.JPanel P3;
    private javax.swing.JTextField P3X;
    private javax.swing.JPanel SALIDA;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel imagen3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_CUERDAPRINCIPAL;
    private javax.swing.JLabel lb_DEFLEXIONPARA10m;
    private javax.swing.JLabel lb_DEFLEXIONPARA1m;
    private javax.swing.JLabel lb_DISTANCIAHORIZ;
    private javax.swing.JLabel lb_ENTRETANGENTE;
    private javax.swing.JLabel lb_EXTERNA;
    private javax.swing.JLabel lb_FLECHA;
    private javax.swing.JLabel lb_LONGITUDDECURVA;
    private javax.swing.JLabel lb_TANGENTE1;
    private javax.swing.JLabel lb_TANGENTE9;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTextField txt_CUERDAPRINCIPAL;
    private javax.swing.JTextField txt_DEFLEXIONPARA10m;
    private javax.swing.JTextField txt_DEFLEXIONPARA1m;
    private javax.swing.JTextField txt_DISTANCIAHORIZ;
    private javax.swing.JTextField txt_ENTRETANGENTE;
    private javax.swing.JTextField txt_EXTERNA;
    private javax.swing.JTextField txt_FLECHA;
    private javax.swing.JTextField txt_LONGITUDDECURVA;
    private javax.swing.JTextField txt_TANGENTE1;
    // End of variables declaration//GEN-END:variables
}
